export const INDIA_STATES = [
  'Andaman and Nicobar Islands',
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chandigarh',
  'Chhattisgarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jammu and Kashmir',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Ladakh',
  'Lakshadweep',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Puducherry',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal'
];

export const PROGRAM_OPTIONS = [
  'B.Tech',
  'B.E.',
  'BCA',
  'BBA',
  'B.Sc',
  'B.Com',
  'BA',
  'Diploma',
  'M.Tech',
  'MCA',
  'MBA',
  'M.Sc'
];

export const DEPARTMENT_OPTIONS = [
  'Computer Science and Engineering',
  'Information Technology',
  'Electronics and Communication Engineering',
  'Electrical Engineering',
  'Mechanical Engineering',
  'Civil Engineering',
  'Chemical Engineering',
  'Biotechnology',
  'Data Science',
  'Artificial Intelligence and Machine Learning',
  'Business Administration',
  'Commerce',
  'Physics',
  'Mathematics',
  'Other'
];

export const SEMESTER_OPTIONS = [
  '1st Semester',
  '2nd Semester',
  '3rd Semester',
  '4th Semester',
  '5th Semester',
  '6th Semester',
  '7th Semester',
  '8th Semester',
  '9th Semester',
  '10th Semester',
  '11th Semester',
  '12th Semester'
];

export const DISTRICTS_BY_STATE: Record<string, string[]> = {
  'Andaman and Nicobar Islands': ['Nicobar', 'North and Middle Andaman', 'South Andaman'],
  'Andhra Pradesh': ['Anantapur', 'Chittoor', 'East Godavari', 'Guntur', 'Krishna', 'Kurnool', 'Prakasam', 'Sri Potti Sriramulu Nellore', 'Visakhapatnam'],
  'Arunachal Pradesh': ['Changlang', 'East Siang', 'Itanagar', 'Papum Pare', 'Tawang'],
  'Assam': ['Cachar', 'Dibrugarh', 'Goalpara', 'Jorhat', 'Kamrup Metro', 'Nagaon', 'Silchar'],
  'Bihar': ['Bhagalpur', 'Darbhanga', 'Gaya', 'Muzaffarpur', 'Nalanda', 'Patna', 'Purnia'],
  'Chandigarh': ['Chandigarh'],
  'Chhattisgarh': ['Bilaspur', 'Dhamtari', 'Durg', 'Jagdalpur', 'Korba', 'Raipur', 'Rajnandgaon'],
  'Dadra and Nagar Haveli and Daman and Diu': ['Daman', 'Diu', 'Silvassa'],
  'Delhi': ['Central Delhi', 'East Delhi', 'New Delhi', 'North Delhi', 'North West Delhi', 'South Delhi', 'West Delhi'],
  'Goa': ['North Goa', 'South Goa'],
  'Gujarat': ['Ahmedabad', 'Bhavnagar', 'Gandhinagar', 'Jamnagar', 'Rajkot', 'Surat', 'Vadodara'],
  'Haryana': ['Ambala', 'Faridabad', 'Gurugram', 'Hisar', 'Karnal', 'Panipat', 'Rohtak'],
  'Himachal Pradesh': ['Hamirpur', 'Kangra', 'Kullu', 'Mandi', 'Shimla', 'Solan', 'Una'],
  'Jammu and Kashmir': ['Anantnag', 'Baramulla', 'Jammu', 'Kathua', 'Pulwama', 'Srinagar', 'Udhampur'],
  'Jharkhand': ['Bokaro', 'Deoghar', 'Dhanbad', 'East Singhbhum', 'Hazaribagh', 'Ranchi'],
  'Karnataka': ['Belagavi', 'Bengaluru Rural', 'Bengaluru Urban', 'Davanagere', 'Mangaluru', 'Mysuru', 'Udupi'],
  'Kerala': ['Alappuzha', 'Ernakulam', 'Kannur', 'Kasaragod', 'Kollam', 'Kottayam', 'Kozhikode', 'Thiruvananthapuram', 'Thrissur'],
  'Ladakh': ['Kargil', 'Leh'],
  'Lakshadweep': ['Kavaratti'],
  'Madhya Pradesh': ['Bhopal', 'Gwalior', 'Indore', 'Jabalpur', 'Rewa', 'Sagar', 'Ujjain'],
  'Maharashtra': ['Aurangabad', 'Kolhapur', 'Mumbai City', 'Mumbai Suburban', 'Nagpur', 'Nashik', 'Pune', 'Thane'],
  'Manipur': ['Bishnupur', 'Churachandpur', 'Imphal East', 'Imphal West', 'Thoubal'],
  'Meghalaya': ['East Khasi Hills', 'Ri Bhoi', 'Shillong', 'Tura', 'West Garo Hills'],
  'Mizoram': ['Aizawl', 'Champhai', 'Kolasib', 'Lunglei', 'Mamit'],
  'Nagaland': ['Dimapur', 'Kohima', 'Mokokchung', 'Phek', 'Tuensang'],
  'Odisha': ['Balasore', 'Cuttack', 'Ganjam', 'Khordha', 'Puri', 'Rourkela', 'Sambalpur'],
  'Puducherry': ['Karaikal', 'Mahe', 'Puducherry', 'Yanam'],
  'Punjab': ['Amritsar', 'Bathinda', 'Jalandhar', 'Ludhiana', 'Mohali', 'Patiala'],
  'Rajasthan': ['Ajmer', 'Alwar', 'Bikaner', 'Jaipur', 'Jodhpur', 'Kota', 'Udaipur'],
  'Sikkim': ['East Sikkim', 'Gangtok', 'Namchi', 'North Sikkim', 'South Sikkim', 'West Sikkim'],
  'Tamil Nadu': ['Chennai', 'Coimbatore', 'Madurai', 'Salem', 'Thanjavur', 'Tiruchirappalli', 'Tirunelveli'],
  'Telangana': ['Adilabad', 'Hyderabad', 'Karimnagar', 'Khammam', 'Nalgonda', 'Warangal'],
  'Tripura': ['Agartala', 'Dhalai', 'Gomati', 'North Tripura', 'West Tripura'],
  'Uttar Pradesh': ['Agra', 'Aligarh', 'Ghaziabad', 'Kanpur Nagar', 'Lucknow', 'Noida', 'Prayagraj', 'Varanasi'],
  'Uttarakhand': ['Dehradun', 'Haridwar', 'Nainital', 'Pauri Garhwal', 'Roorkee', 'Udham Singh Nagar'],
  'West Bengal': ['Alipurduar', 'Bankura', 'Birbhum', 'Cooch Behar', 'Darjeeling', 'East Midnapore', 'Hooghly', 'Howrah', 'Jalpaiguri', 'Kolkata', 'Malda', 'Murshidabad', 'Nadia', 'North 24 Parganas', 'Paschim Bardhaman', 'Purba Bardhaman', 'Purulia', 'South 24 Parganas', 'West Midnapore']
};
